batch_size : 12 # modules.py -> line: 378 -> group size 4
data_resize : True
#data_dir: '/_yucheng/dataSet/CelebAMask-HQ/CelebAMask-HQ/CelebA-HQ-img'
data_dir: '/home/disanda/Desktop/dataSet/CelebAMask-HQ/img-30000/CelebA-HQ-img/'
tensorboard_log_dir : './runs_2020_mar03/stylegan2_512x512'
tensorboard_image_interval : 100
output: './runs_2020_mar03'
checkpoint_dir : './checkpoints/stylegan2_512x512'
checkpoint_interval : 1000

channels : [16, 32, 64, 128, 256, 512, 512, 512]















