

batch_size : 24
data_resize : True
data_dir: '/_yucheng/dataSet/CelebAMask-HQ/CelebAMask-HQ/CelebA-HQ-img'
tensorboard_log_dir : './runs/stylegan2_512x512'
tensorboard_image_interval : 100
checkpoint_dir : './checkpoints/stylegan2_512x512'
checkpoint_interval : 1000

channels : [16, 32, 64, 128, 256, 512, 512, 512]














